import * as Schema from "effect/Schema";
import { AkeruMemoryArchiveV1, AkeruMemoryArchiveV2 } from "./akeruMemory/transfer.ts";

export const AkeruMemoryArchive = Schema.Union([AkeruMemoryArchiveV1, AkeruMemoryArchiveV2]);

export type AkeruMemoryArchive = typeof AkeruMemoryArchive.Type;
export {
  AKERU_MEMORY_PACKET_MAX_FACTS,
  AKERU_MEMORY_PACKET_MAX_CHARS,
  AKERU_MEMORY_PACKET_MAX_ESTIMATED_TOKENS,
  AKERU_MEMORY_FACT_MAX_CHARS,
  AKERU_USER_MEMORY_MAX_CHARS,
  AKERU_BOT_MEMORY_MAX_CHARS,
  AKERU_GROUP_MEMORY_MAX_CHARS,
  AkeruMemoryId,
  AkeruMemoryRootId,
  AkeruMemoryCandidateId,
  AkeruMemoryTenantId,
  AkeruMemoryUserId,
  AkeruMemoryEntityId,
  AkeruMemoryPartitionId,
  AkeruMemoryScope,
  AkeruMemoryVisibility,
  AkeruMemoryApprovalState,
  AkeruMemoryCandidateStatus,
  AkeruMemoryCandidateUpdate,
  AkeruMemoryTargetScope,
  AkeruMemoryDeletionState,
  AkeruMemoryKind,
  AkeruMemoryEntityKind,
  AkeruMemoryConfidence,
  AkeruMemoryPartition,
  AkeruMemoryRevision,
  AkeruMemoryCandidate,
  AkeruMemoryCandidateDecision,
  AkeruMemoryDecisionReceipt,
  AKERU_MEMORY_APPROVAL_REQUESTED_ACTIVITY,
  AKERU_MEMORY_APPROVAL_RESOLVED_ACTIVITY,
  AkeruMemoryApprovalRequest,
} from "./akeruMemory/base.ts";
export {
  AkeruMemoryDocumentTarget,
  AkeruMemoryFileOperation,
  AkeruMemoryDocument,
  AkeruBotMemorySnapshot,
  AkeruMemoryFileMutationInput,
  AkeruMemoryFileMutationResult,
  AkeruMemoryDocumentsInspectInput,
  AkeruMemoryDocumentsSnapshot,
  AkeruMemoryDocumentReplaceInput,
  AkeruMemoryObservationsClearInput,
} from "./akeruMemory/documents.ts";
export {
  AkeruMemoryShareScope,
  AkeruMemoryArchiveFile,
  AkeruMemoryArchiveV1,
  AkeruMemoryArchiveTarget,
  AkeruMemoryArchiveRevision,
  AkeruMemoryInspectInput,
  AkeruConversationMemoryRecord,
  AkeruConversationMemorySnapshot,
  AkeruMarkdownMemoryArchiveDocument,
  AkeruMarkdownMemoryArchiveV3,
  AkeruMarkdownMemoryExportInput,
  AkeruMarkdownMemoryImportPreviewInput,
  AkeruMarkdownMemoryImportPreviewItem,
  AkeruMarkdownMemoryImportPreview,
  AkeruMarkdownMemoryImportApplyInput,
  AkeruMarkdownMemoryImportApplyResult,
  AkeruMemoryArchiveConversation,
  AkeruMemoryArchiveV2,
  AkeruMemorySnapshot,
  AkeruMemoryExportInput,
  AkeruMemoryImportClassification,
  AkeruMemoryImportPreviewItem,
  AkeruMemoryImportPreviewInput,
  AkeruMemoryImportPreview,
  AkeruMemoryImportApplyInput,
  AkeruMemoryImportApplyResult,
} from "./akeruMemory/transfer.ts";
export {
  AkeruMemoryMutation,
  AkeruMemoryMutateInput,
  AkeruMemoryMutationResult,
  AkeruMemoryFactsListInput,
  AkeruMemoryFactRead,
  AkeruMemoryFactsListResult,
  AkeruMemoryOperationError,
  AkeruMemoryPacketFact,
  AkeruMemoryPacket,
  AkeruMemoryThreadAccess,
} from "./akeruMemory/facts.ts";
