import * as Schema from "effect/Schema";
import { RuntimeTurnState } from "./providerRuntime/base.ts";
import {
  ProviderRuntimeSessionStartedEvent,
  ProviderRuntimeSessionConfiguredEvent,
  ProviderRuntimeSessionStateChangedEvent,
  ProviderRuntimeSessionExitedEvent,
  ProviderRuntimeThreadStartedEvent,
  ProviderRuntimeThreadStateChangedEvent,
  ProviderRuntimeThreadMetadataUpdatedEvent,
  ProviderRuntimeThreadTokenUsageUpdatedEvent,
  ProviderRuntimeThreadRealtimeStartedEvent,
  ProviderRuntimeThreadRealtimeItemAddedEvent,
  ProviderRuntimeThreadRealtimeAudioDeltaEvent,
  ProviderRuntimeThreadRealtimeErrorEvent,
  ProviderRuntimeThreadRealtimeClosedEvent,
  ProviderRuntimeAuthStatusEvent,
  ProviderRuntimeAccountUpdatedEvent,
  ProviderRuntimeAccountRateLimitsUpdatedEvent,
  ProviderRuntimeMcpStatusUpdatedEvent,
  ProviderRuntimeMcpOauthCompletedEvent,
  ProviderRuntimeModelReroutedEvent,
  ProviderRuntimeConfigWarningEvent,
  ProviderRuntimeDeprecationNoticeEvent,
  ProviderRuntimeFilesPersistedEvent,
} from "./providerRuntime/sessionEvents.ts";
import {
  ProviderRuntimeTurnStartedEvent,
  ProviderRuntimeTurnCompletedEvent,
  ProviderRuntimeTurnAbortedEvent,
  ProviderRuntimeTurnPlanUpdatedEvent,
  ProviderRuntimeTurnProposedDeltaEvent,
  ProviderRuntimeTurnProposedCompletedEvent,
  ProviderRuntimeTurnDiffUpdatedEvent,
  ProviderRuntimeItemStartedEvent,
  ProviderRuntimeItemUpdatedEvent,
  ProviderRuntimeItemCompletedEvent,
  ProviderRuntimeContentDeltaEvent,
  ProviderRuntimeTaskStartedEvent,
  ProviderRuntimeTaskProgressEvent,
  ProviderRuntimeTaskUpdatedEvent,
  ProviderRuntimeTaskCompletedEvent,
  ProviderRuntimeHookStartedEvent,
  ProviderRuntimeHookProgressEvent,
  ProviderRuntimeHookCompletedEvent,
  ProviderRuntimeToolProgressEvent,
  ProviderRuntimeToolSummaryEvent,
  ProviderRuntimeToolDeniedEvent,
  ProviderRuntimeToolReceiptEvent,
  ProviderRuntimeWarningEvent,
  ProviderRuntimeErrorEvent,
} from "./providerRuntime/turnEvents.ts";
import {
  ProviderRuntimeRequestOpenedEvent,
  ProviderRuntimeRequestResolvedEvent,
  ProviderRuntimeUserInputRequestedEvent,
  ProviderRuntimeUserInputResolvedEvent,
} from "./providerRuntime/requestEvents.ts";

export const ProviderRuntimeEventV2 = Schema.Union([
  ProviderRuntimeSessionStartedEvent,
  ProviderRuntimeSessionConfiguredEvent,
  ProviderRuntimeSessionStateChangedEvent,
  ProviderRuntimeSessionExitedEvent,
  ProviderRuntimeThreadStartedEvent,
  ProviderRuntimeThreadStateChangedEvent,
  ProviderRuntimeThreadMetadataUpdatedEvent,
  ProviderRuntimeThreadTokenUsageUpdatedEvent,
  ProviderRuntimeThreadRealtimeStartedEvent,
  ProviderRuntimeThreadRealtimeItemAddedEvent,
  ProviderRuntimeThreadRealtimeAudioDeltaEvent,
  ProviderRuntimeThreadRealtimeErrorEvent,
  ProviderRuntimeThreadRealtimeClosedEvent,
  ProviderRuntimeTurnStartedEvent,
  ProviderRuntimeTurnCompletedEvent,
  ProviderRuntimeTurnAbortedEvent,
  ProviderRuntimeTurnPlanUpdatedEvent,
  ProviderRuntimeTurnProposedDeltaEvent,
  ProviderRuntimeTurnProposedCompletedEvent,
  ProviderRuntimeTurnDiffUpdatedEvent,
  ProviderRuntimeItemStartedEvent,
  ProviderRuntimeItemUpdatedEvent,
  ProviderRuntimeItemCompletedEvent,
  ProviderRuntimeContentDeltaEvent,
  ProviderRuntimeRequestOpenedEvent,
  ProviderRuntimeRequestResolvedEvent,
  ProviderRuntimeUserInputRequestedEvent,
  ProviderRuntimeUserInputResolvedEvent,
  ProviderRuntimeTaskStartedEvent,
  ProviderRuntimeTaskProgressEvent,
  ProviderRuntimeTaskUpdatedEvent,
  ProviderRuntimeTaskCompletedEvent,
  ProviderRuntimeHookStartedEvent,
  ProviderRuntimeHookProgressEvent,
  ProviderRuntimeHookCompletedEvent,
  ProviderRuntimeToolProgressEvent,
  ProviderRuntimeToolSummaryEvent,
  ProviderRuntimeAuthStatusEvent,
  ProviderRuntimeAccountUpdatedEvent,
  ProviderRuntimeAccountRateLimitsUpdatedEvent,
  ProviderRuntimeMcpStatusUpdatedEvent,
  ProviderRuntimeMcpOauthCompletedEvent,
  ProviderRuntimeModelReroutedEvent,
  ProviderRuntimeConfigWarningEvent,
  ProviderRuntimeDeprecationNoticeEvent,
  ProviderRuntimeFilesPersistedEvent,
  ProviderRuntimeToolDeniedEvent,
  ProviderRuntimeToolReceiptEvent,
  ProviderRuntimeWarningEvent,
  ProviderRuntimeErrorEvent,
]);

export type ProviderRuntimeEventV2 = typeof ProviderRuntimeEventV2.Type;

export const ProviderRuntimeEvent = ProviderRuntimeEventV2;

export type ProviderRuntimeEvent = ProviderRuntimeEventV2;

export const ProviderRuntimeTurnStatus = RuntimeTurnState;

export type ProviderRuntimeTurnStatus = RuntimeTurnState;

export {
  type RuntimeEventRawSource,
  RuntimeEventRaw,
  type ProviderRequestId,
  type ProviderRefs,
  type RuntimeSessionState,
  type RuntimeThreadState,
  type RuntimeTurnState,
  type RuntimePlanStepStatus,
  type RuntimeItemStatus,
  type RuntimeContentStreamKind,
  type RuntimeSessionExitKind,
  type RuntimeErrorClass,
  TOOL_LIFECYCLE_ITEM_TYPES,
  ToolLifecycleItemType,
  isToolLifecycleItemType,
  CanonicalItemType,
  CanonicalRequestType,
  type ProviderRuntimeEventType,
  type ProviderRuntimeEventBase,
} from "./providerRuntime/base.ts";

export {
  type SessionStartedPayload,
  type SessionConfiguredPayload,
  type SessionStateChangedPayload,
  type SessionExitedPayload,
  type ThreadStartedPayload,
  type ThreadStateChangedPayload,
  type ThreadMetadataUpdatedPayload,
  ThreadTokenUsageSnapshot,
  type ThreadTokenUsageUpdatedPayload,
  type ThreadRealtimeStartedPayload,
  type ThreadRealtimeItemAddedPayload,
  type ThreadRealtimeAudioDeltaPayload,
  type ThreadRealtimeErrorPayload,
  type ThreadRealtimeClosedPayload,
  type AuthStatusPayload,
  type AccountUpdatedPayload,
  type AccountRateLimitsUpdatedPayload,
  type McpStatusUpdatedPayload,
  type McpOauthCompletedPayload,
  type ModelReroutedPayload,
  type ConfigWarningPayload,
  type DeprecationNoticePayload,
  type FilesPersistedPayload,
  type ProviderRuntimeSessionStartedEvent,
  type ProviderRuntimeSessionConfiguredEvent,
  type ProviderRuntimeSessionStateChangedEvent,
  type ProviderRuntimeSessionExitedEvent,
  type ProviderRuntimeThreadStartedEvent,
  type ProviderRuntimeThreadStateChangedEvent,
  type ProviderRuntimeThreadMetadataUpdatedEvent,
  type ProviderRuntimeThreadTokenUsageUpdatedEvent,
  type ProviderRuntimeThreadRealtimeStartedEvent,
  type ProviderRuntimeThreadRealtimeItemAddedEvent,
  type ProviderRuntimeThreadRealtimeAudioDeltaEvent,
  type ProviderRuntimeThreadRealtimeErrorEvent,
  type ProviderRuntimeThreadRealtimeClosedEvent,
  type ProviderRuntimeAuthStatusEvent,
  type ProviderRuntimeAccountUpdatedEvent,
  type ProviderRuntimeAccountRateLimitsUpdatedEvent,
  type ProviderRuntimeMcpStatusUpdatedEvent,
  type ProviderRuntimeMcpOauthCompletedEvent,
  type ProviderRuntimeModelReroutedEvent,
  type ProviderRuntimeConfigWarningEvent,
  type ProviderRuntimeDeprecationNoticeEvent,
  type ProviderRuntimeFilesPersistedEvent,
} from "./providerRuntime/sessionEvents.ts";

export {
  type TurnStartedPayload,
  type TurnCompletedPayload,
  type TurnAbortedPayload,
  type RuntimePlanStep,
  type TurnPlanUpdatedPayload,
  type TurnProposedDeltaPayload,
  type TurnProposedCompletedPayload,
  type TurnDiffUpdatedPayload,
  ItemLifecyclePayload,
  type ContentDeltaPayload,
  RuntimeTaskUsage,
  TaskWorkflowPhase,
  TaskRunHandles,
  MONITOR_TASK_TYPES,
  INERT_TASK_TYPES,
  classifyTaskAgentKind,
  TaskAgentLinkage,
  type TaskStartedPayload,
  RuntimeTaskStatus,
  type TaskProgressPayload,
  type TaskUpdatedPayload,
  type TaskCompletedPayload,
  type HookStartedPayload,
  type HookProgressPayload,
  type HookCompletedPayload,
  type ToolProgressPayload,
  type ToolSummaryPayload,
  type ToolDeniedPayload,
  type ToolReceiptPayload,
  type RuntimeWarningPayload,
  type RuntimeErrorPayload,
  type ProviderRuntimeTurnStartedEvent,
  type ProviderRuntimeTurnCompletedEvent,
  type ProviderRuntimeTurnAbortedEvent,
  type ProviderRuntimeTurnPlanUpdatedEvent,
  type ProviderRuntimeTurnProposedDeltaEvent,
  type ProviderRuntimeTurnProposedCompletedEvent,
  type ProviderRuntimeTurnDiffUpdatedEvent,
  type ProviderRuntimeItemStartedEvent,
  type ProviderRuntimeItemUpdatedEvent,
  type ProviderRuntimeItemCompletedEvent,
  type ProviderRuntimeContentDeltaEvent,
  type ProviderRuntimeTaskStartedEvent,
  type ProviderRuntimeTaskProgressEvent,
  type ProviderRuntimeTaskUpdatedEvent,
  type ProviderRuntimeTaskCompletedEvent,
  type ProviderRuntimeHookStartedEvent,
  type ProviderRuntimeHookProgressEvent,
  type ProviderRuntimeHookCompletedEvent,
  type ProviderRuntimeToolProgressEvent,
  type ProviderRuntimeToolSummaryEvent,
  type ProviderRuntimeToolDeniedEvent,
  type ProviderRuntimeToolReceiptEvent,
  type ProviderRuntimeWarningEvent,
  type ProviderRuntimeErrorEvent,
} from "./providerRuntime/turnEvents.ts";

export {
  type RequestOpenedPayload,
  type RequestResolvedPayload,
  type UserInputQuestionOption,
  UserInputQuestion,
  type UserInputRequestedPayload,
  type UserInputResolvedPayload,
  type ProviderRuntimeRequestOpenedEvent,
  type ProviderRuntimeRequestResolvedEvent,
  type ProviderRuntimeUserInputRequestedEvent,
  type ProviderRuntimeUserInputResolvedEvent,
} from "./providerRuntime/requestEvents.ts";
