import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  BotCreatedPayload as ContractsBotCreatedPayloadSchema,
  BotUpdatedPayload as ContractsBotUpdatedPayloadSchema,
  BotArchivedPayload as ContractsBotArchivedPayloadSchema,
  BotRestoredPayload as ContractsBotRestoredPayloadSchema,
  GroupCreatedPayload as ContractsGroupCreatedPayloadSchema,
  GroupRenamedPayload as ContractsGroupRenamedPayloadSchema,
  GroupDeletedPayload as ContractsGroupDeletedPayloadSchema,
  GroupMemberAssignedPayload as ContractsGroupMemberAssignedPayloadSchema,
  GroupMemberUnassignedPayload as ContractsGroupMemberUnassignedPayloadSchema,
  GroupPersonAssignedPayload as ContractsGroupPersonAssignedPayloadSchema,
  GroupPersonUnassignedPayload as ContractsGroupPersonUnassignedPayloadSchema,
  GroupBossSetPayload as ContractsGroupBossSetPayloadSchema,
  McpServerCreatedPayload as ContractsMcpServerCreatedPayloadSchema,
  McpServerUpdatedPayload as ContractsMcpServerUpdatedPayloadSchema,
  McpServerDeletedPayload as ContractsMcpServerDeletedPayloadSchema,
  McpServerEnabledPayload as ContractsMcpServerEnabledPayloadSchema,
  McpServerDisabledPayload as ContractsMcpServerDisabledPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadOwnershipUpdatedPayload as ContractsThreadOwnershipUpdatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadMessageReactionSetPayload as ContractsThreadMessageReactionSetPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const BotCreatedPayload = ContractsBotCreatedPayloadSchema;
export const BotUpdatedPayload = ContractsBotUpdatedPayloadSchema;
export const BotArchivedPayload = ContractsBotArchivedPayloadSchema;
export const BotRestoredPayload = ContractsBotRestoredPayloadSchema;
export const GroupCreatedPayload = ContractsGroupCreatedPayloadSchema;
export const GroupRenamedPayload = ContractsGroupRenamedPayloadSchema;
export const GroupDeletedPayload = ContractsGroupDeletedPayloadSchema;
export const GroupMemberAssignedPayload = ContractsGroupMemberAssignedPayloadSchema;
export const GroupMemberUnassignedPayload = ContractsGroupMemberUnassignedPayloadSchema;
export const GroupPersonAssignedPayload = ContractsGroupPersonAssignedPayloadSchema;
export const GroupPersonUnassignedPayload = ContractsGroupPersonUnassignedPayloadSchema;
export const GroupBossSetPayload = ContractsGroupBossSetPayloadSchema;
export const McpServerCreatedPayload = ContractsMcpServerCreatedPayloadSchema;
export const McpServerUpdatedPayload = ContractsMcpServerUpdatedPayloadSchema;
export const McpServerDeletedPayload = ContractsMcpServerDeletedPayloadSchema;
export const McpServerEnabledPayload = ContractsMcpServerEnabledPayloadSchema;
export const McpServerDisabledPayload = ContractsMcpServerDisabledPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadOwnershipUpdatedPayload = ContractsThreadOwnershipUpdatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadMessageReactionSetPayload = ContractsThreadMessageReactionSetPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
