export const WS_METHODS = {
  // Project registry methods
  projectsList: "projects.list",
  projectsListEntries: "projects.listEntries",
  projectsReadFile: "projects.readFile",
  projectsSearchEntries: "projects.searchEntries",
  projectsWriteFile: "projects.writeFile",

  // Shell methods
  shellOpenInEditor: "shell.openInEditor",
  shellRevealAttachment: "shell.revealAttachment",

  // Filesystem methods
  assetsCreateUrl: "assets.createUrl",
  attachmentsCreateUploadUrl: "attachments.createUploadUrl",
  attachmentsDelete: "attachments.delete",

  // Provider methods
  providerUploadFeedback: "provider.uploadFeedback",

  computerGetState: "computer.getState",
  computerOpen: "computer.open",
  computerAcquire: "computer.acquire",
  computerInput: "computer.input",
  computerRelease: "computer.release",
  computerClose: "computer.close",
  computerStop: "computer.stop",
  computerEvents: "computer.events",

  // Preview methods
  previewOpen: "preview.open",
  previewNavigate: "preview.navigate",
  previewResize: "preview.resize",
  previewRefresh: "preview.refresh",
  previewClose: "preview.close",
  previewList: "preview.list",
  previewReportStatus: "preview.reportStatus",
  previewAutomationConnect: "previewAutomation.connect",
  previewAutomationRespond: "previewAutomation.respond",
  previewAutomationFocusHost: "previewAutomation.focusHost",

  // Server meta
  serverProbe: "server.probe",
  serverGetConfig: "server.getConfig",
  serverRefreshProviders: "server.refreshProviders",
  serverUpdateProvider: "server.updateProvider",
  serverUpdateServer: "server.updateServer",
  serverUpdateServerWithProgress: "server.updateServerWithProgress",
  serverUpsertKeybinding: "server.upsertKeybinding",
  serverRemoveKeybinding: "server.removeKeybinding",
  serverGetSettings: "server.getSettings",
  serverUpdateSettings: "server.updateSettings",
  composioGetStatus: "composio.getStatus",
  composioConfigure: "composio.configure",
  composioRemove: "composio.remove",
  composioSearchToolkits: "composio.searchToolkits",
  composioAuthorize: "composio.authorize",
  composioDisconnect: "composio.disconnect",
  subscriptionAuthList: "subscriptionAuth.list",
  subscriptionAuthStart: "subscriptionAuth.start",
  subscriptionAuthPoll: "subscriptionAuth.poll",
  subscriptionAuthComplete: "subscriptionAuth.complete",
  subscriptionAuthCancel: "subscriptionAuth.cancel",
  subscriptionAuthLogout: "subscriptionAuth.logout",
  subscriptionAuthHealthTest: "subscriptionAuth.healthTest",
  subscriptionAuthSetAccountOrder: "subscriptionAuth.setAccountOrder",

  // Image generation providers
  imageProviderList: "imageProvider.list",
  imageProviderHealthTest: "imageProvider.healthTest",
  mcpServerAuthenticate: "mcpServer.authenticate",
  botInboxList: "botInbox.list",
  botInboxResolve: "botInbox.resolve",
  voiceProviders: "voice.providers",
  voiceConnect: "voice.connect",
  voiceDisconnect: "voice.disconnect",
  voiceTest: "voice.test",
  voiceListVoices: "voice.listVoices",
  voiceTranscribe: "voice.transcribe",
  voiceSynthesize: "voice.synthesize",
  voiceCancel: "voice.cancel",
  voiceCallGet: "voiceCall.get",
  voiceCallStart: "voiceCall.start",
  voiceCallHangup: "voiceCall.hangup",
  serverGetTraceDiagnostics: "server.getTraceDiagnostics",
  serverGetProcessDiagnostics: "server.getProcessDiagnostics",
  serverGetProcessResourceHistory: "server.getProcessResourceHistory",
  serverGetResourceTelemetryHistory: "server.getResourceTelemetryHistory",
  serverRetryResourceTelemetry: "server.retryResourceTelemetry",
  serverSignalProcess: "server.signalProcess",
  serverReportClientActivity: "server.reportClientActivity",
  serverReportHostPowerState: "server.reportHostPowerState",
  serverGetBackgroundPolicy: "server.getBackgroundPolicy",
  serverGetUsageSummary: "server.getUsageSummary",
  serverGetRemoteDoctor: "server.getRemoteDoctor",
  serverRepairRemoteDoctor: "server.repairRemoteDoctor",
  memoryExport: "memory.documents.export",
  memoryImportPreview: "memory.documents.importPreview",
  memoryImportApply: "memory.documents.importApply",
  memoryArchiveExport: "memory.archive.export",
  memoryArchivePreviewImport: "memory.archive.previewImport",
  memoryArchiveApplyImport: "memory.archive.applyImport",
  memoryFactsList: "memory.facts.list",
  memoryFactMutate: "memory.facts.mutate",
  memoryDocumentsInspect: "memory.documents.inspect",
  memoryDocumentReplace: "memory.document.replace",
  memoryObservationsClear: "memory.observations.clear",
  botUsage: "bot.usage",
  portabilityExport: "portability.export",
  portabilityPreviewImport: "portability.previewImport",
  portabilityApplyImport: "portability.applyImport",
  routinesListRuns: "routines.listRuns",
  routinesListThreadRuns: "routines.listThreadRuns",

  // Streaming subscriptions
  subscribePreviewEvents: "subscribePreviewEvents",
  subscribeDiscoveredLocalServers: "subscribeDiscoveredLocalServers",
  subscribeServerConfig: "subscribeServerConfig",
  subscribeServerLifecycle: "subscribeServerLifecycle",
  subscribeAuthAccess: "subscribeAuthAccess",
  subscribeBackgroundPolicy: "subscribeBackgroundPolicy",
  subscribeResourceTelemetry: "subscribeResourceTelemetry",
} as const;
