/**
 * Theme steps declared in styles/scale-tokens.css. `cn` needs them so a later
 * `text-11px` or `w-min-300px-vw-2rem` replaces an earlier class from the same
 * group instead of being kept alongside it or read as a color.
 */
export const scaleTheme = {
  text: [
    "7px",
    "8px",
    "9px",
    "10px",
    "11px",
    "12px",
    "13px",
    "15px",
    "17px",
    "26px",
    "0.6875rem",
    "1em",
  ],
  tracking: [
    "caps",
    "caps-wide",
    "caps-wider",
    "caps-widest",
    "title-xs",
    "title-sm",
    "title",
    "title-lg",
  ],
  leading: ["copy", "copy-tight"],
  font: ["emoji"],
  spacing: [
    "0.2em",
    "0.25em",
    "1em",
    "1.6em",
    "0.4rem",
    "0.65rem",
    "0.9rem",
    "48ch",
    "80dvh",
    "86vh",
    "92vh",
    "92vw",
    "dvh-2rem",
    "full-plus-1rem",
    "min-full-30rem",
    "min-300px-vw-2rem",
    "min-440px-vw-2rem",
    "min-520px-vw-2rem",
    "min-22.5rem-vw-2rem",
    "min-26rem-vw-2rem",
    "min-34rem-vw-2rem",
    "min-36rem-vw-2rem",
    "min-40rem-vw-2rem",
    "min-92vw-24rem",
    "min-42rem-pct-2.5rem",
    "min-46rem-pct-2rem",
    "min-48rem-pct-2rem",
    "min-21.625rem-dvh-2rem",
    "min-42rem-dvh-6rem",
    "min-24rem-40dvh",
    "min-28rem-70vh",
    "min-32rem-90dvh",
    "min-36rem-90dvh",
    "min-42rem-90dvh",
    "min-44rem-88dvh",
    "min-45dvh-22rem",
    "min-48rem-90dvh",
    "min-64vh-44rem",
    "min-68vh-48rem",
    "gutter-48rem",
    "gutter-48rem-wide",
    "safe-left-0.75rem",
    "safe-right-0.75rem",
    "safe-left-1.25rem",
    "safe-right-1.25rem",
    "titlebar-controls-end",
    "topbar-spacer",
    "composer-overlap-1.5",
  ],
  radius: ["1px", "5px", "10px", "0.45em", "1.65rem", "2rem"],
  shadow: [
    "hairline",
    "hairline-lifted",
    "card-rest",
    "card-hover",
    "peek",
    "composer-float",
    "preview-frame",
    "inset-highlight",
  ],
  blur: ["1px", "2px"],
  animate: ["prompt-stash-count-enter", "provider-update-pill-countdown"],
  color: ["popover-highlight", "sidebar-wash"],
};

export const scaleClassGroups = {
  "grid-cols": [
    {
      "grid-cols": [
        "1fr-auto",
        "1fr-2fr",
        "1fr-7rem",
        "1fr-10rem",
        "1fr-10rem-auto",
        "auto-1fr",
        "auto-grow",
        "grow-auto-auto",
        "grow-auto-grow",
        "grow-1.2grow",
        "4ch-4ch",
        "8rem-1fr",
        "12rem-1fr",
        "18rem-1fr",
        "10rem-1fr-7rem",
        "legend-row",
        "fill-15rem",
      ],
    },
  ],
  "grid-rows": [{ "grid-rows": ["collapsed", "expanded"] }],
  transition: [
    {
      transition: [
        "height",
        "top",
        "padding",
        "padding-left",
        "stroke-dashoffset",
        "grid-rows",
        "color-opacity",
        "transform-opacity",
        "border-shadow",
        "border-bg-shadow",
        "bg-color-shadow",
        "composer-shape",
      ],
    },
  ],
};
